spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://springboot-db.chqmglbcz4ky.ap-northeast-2.rds.amazonaws.com:3306/shopping
    username: Admin
    password: aa1237113
  devtools:
    livereload:
      enabled: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: true
    generate-ddl: true
    show-sql: true

cloud:
  aws:
    credentials:
      access-key: AKIAQFVGVOED66R6SD2C
      secret-key: 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
    s3:
      bucket: shop-test-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false




itemImgLocation: /Users/hyeonseung/Desktop/item/
uploadPath: file:///Users/hyeonseung/Desktop/


